apiVersion: v1
kind: Service

metadata:
  name: zarrin-platform-service

spec:

  type: NodePort

  selector:
    app: zarrin-platform

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
